#!/bin/bash
# 快速安装命令 - 请在 macOS 终端中运行

echo "================================================"
echo "  快速安装 Homebrew 和 Docker Desktop"
echo "================================================"
echo ""
echo "请按以下步骤操作："
echo ""
echo "📋 第一步：安装 Homebrew"
echo "----------------------------------------------"
echo "复制以下命令到终端运行（需要输入管理员密码）："
echo ""
echo '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
echo ""
echo "安装完成后，根据提示添加 Homebrew 到 PATH："
echo ""
echo "# 如果是 Apple Silicon (M1/M2/M3)："
echo 'echo "eval \"\$(/opt/homebrew/bin/brew shellenv)\"" >> ~/.zprofile'
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"'
echo ""
echo "# 如果是 Intel 芯片："
echo 'echo "eval \"\$(/usr/local/bin/brew shellenv)\"" >> ~/.zprofile'
echo 'eval "$(/usr/local/bin/brew shellenv)"'
echo ""
echo "================================================"
echo ""
echo "📋 第二步：验证 Homebrew 安装"
echo "----------------------------------------------"
echo "brew --version"
echo ""
echo "================================================"
echo ""
echo "📋 第三步：安装 Docker Desktop"
echo "----------------------------------------------"
echo "brew install --cask docker"
echo ""
echo "================================================"
echo ""
echo "📋 第四步：启动 Docker Desktop"
echo "----------------------------------------------"
echo "open -a Docker"
echo ""
echo "等待 Docker 启动完成（右上角出现鲸鱼图标）"
echo ""
echo "================================================"
echo ""
echo "📋 第五步：验证 Docker 安装"
echo "----------------------------------------------"
echo "docker --version"
echo "docker-compose --version"
echo "docker info"
echo ""
echo "================================================"
echo ""
echo "🎉 安装完成后，开始构建 RustDesk："
echo "----------------------------------------------"
echo "cd /Volumes/拓展盘/软件/远程二开项目/rustdesk-client"
echo "./docker-build.sh build      # 构建镜像（首次约 15 分钟）"
echo "./docker-build.sh start      # 启动容器"
echo "./docker-build.sh compile    # 编译 RustDesk"
echo ""
echo "================================================"
